language: python
python:
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: dospac87
  password:
    secure: XpYEedn7XcPTh6H4+rRBCrI5yaqM0lA6XmN4D/d8DO9Tdu+CeD39OMiLTeOqctJak9QHa8c7ZIjgHo0H0L3nbh9HN9F2LEeAilb7lk+rsTeRz6UMx33nUKX5fYWQPeNb+dvT6R3eTx0N+9rRV8iz1/EO5asFWSJmPHg8dCOtuhENcDVXvJE5K/M5BK1FJvF1i0bSg4CpOMqVUaj5IIBStWsyrAgLZKDVyhndNoy1ELqfHN/cRexzOWeThpKEv4HSZTKyxh0JUoAALGpocfrpW3tjadStgMwL29mHle0muYtZb7dLgk424YZkyNrL/EriaiUfk3h8y+1iXcLJIJ1z3KS/QVspSJoFrdADql7Q8+vjwaAFcrHiF8mH23zUX2gDEq50ZpiMQb3YwqRpXbnK4ODMf0go5LKN9NKqjBO5If0isQGHAn6M9lOtfrBehM/JXscP7qrrrsXn0vwmfWmzZLAHvbLUFhK9dPKivbF/tIpf7SRKHUo5rr9RwVq+BhSl5+ryb6Cpj6s5SsTPmKdxQWqmrBQm6QqhST0YA/TxVaVPEzZ4TdxJ+P1f7ZwJqPH/ksYApdlkvoTDZBjOSNpNB1hARhKcXsfH1j/IU192st1kAr8l9rwQ2fZEJ0kEaVCMu2JSJHJHRXlZsMgtmjVUKDYiG3BgCM6CYJY5wNUinDg=
    tags: true
    repo: dospac87/phenotype
    python: 3.7
    dist: xenial
    sudo: true
